version: 1.0.{build}
image: Ubuntu2004

environment:
  ANDROID_HOME: /usr/local/android-sdk

install:
  - sudo apt-get update
  - sudo apt-get install -y openjdk-11-jdk
  - wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
  - unzip -q commandlinetools-linux-9477386_latest.zip
  - mkdir -p $ANDROID_HOME/cmdline-tools
  - mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
  - $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
  - echo "sdk.dir=$ANDROID_HOME" > local.properties

build_script:
  - chmod +x gradlew
  - ./gradlew assembleDebug

artifacts:
  - path: app/build/outputs/apk/debug/*.apk
    name: APK
